Practice2
andrew-budnitskiy/OI_Practice pull request #4
Opened 2021-06-27 10:17 UTC by andrew-budnitskiy

2021-06-28 06:10 UTC, vasilevkin commented
create a new repo for Practice 2

2021-06-28 06:11 UTC, vasilevkin commented on Cats/Cats.xcodeproj/project.pbxproj
> +// !$*UTF8*$!
do not include this file to the pr

2021-06-28 06:11 UTC, vasilevkin commented on Cats/Cats.xcodeproj/project.xcworkspace/contents.xcworkspacedata
> +<?xml version="1.0" encoding="UTF-8"?>
do not include this file to the pr

2021-06-28 06:11 UTC, vasilevkin commented on Cats/Cats.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
do not include this file to the pr

2021-06-28 06:11 UTC, vasilevkin commented on Cats/Cats/AppDelegate.swift
> +//
do not include this file to the pr

2021-06-28 06:12 UTC, vasilevkin commented on Cats/Cats/Info.plist
> +<?xml version="1.0" encoding="UTF-8"?>
do not include this file to the pr

2021-06-28 06:12 UTC, vasilevkin commented on Cats/Cats/SceneDelegate.swift
> +//
do not include this file to the pr

2021-06-28 06:14 UTC, vasilevkin requested changes
only your changes should be in the pr

2021-06-29 07:43 UTC, closed without merging

2021-06-29 09:00 UTC, vasilevkin commented
please do not close pr.
make it draft and edit.

2021-06-29 11:25 UTC, andrew-budnitskiy commented
According your comment I create new repo and I’m waiting for your collaborator’s confirm now.

Отправлено с iPhone

> 29 июня 2021 г., в 14:00, Sergey Vasilevkin ***@***.***> написал(а):
> 
> ﻿
> please do not close pr.
> make it draft and edit.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.